default: &default
  url: redis://127.0.0.1:6379
  db: 0

development:
  << : *default
  adapter: redis

test:
  << : *default
  adapter: redis
  
production:
  << : *default
  adapter: redis
  url: "redis://127.0.0.1:6379/0"
  channel_prefix: multiplayer_pacman_production
