default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://redis:6379/0") %>
  channel_prefix: multiplayer_pacman

development:
  <<: *default

test:
  <<: *default
  channel_prefix: multiplayer_pacman_test

production:
  <<: *default
  channel_prefix: multiplayer_pacman_production

