development:
  adapter: redis
  redis-host: 127.0.0.1
  redis-port: 6379
  
test:
  adapter: redis
  
production:
  adapter: redis
  url: "redis://127.0.0.1:6379/1"
  channel_prefix: multiplayer_pacman_production
